/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/cake.gltf -o components/Cake.jsx -r public
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cake(props) {
  const { nodes, materials } = useGLTF('/models/cake.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.138, 0, 0.24]} rotation={[-Math.PI, Math.PI / 3, -Math.PI]}>
        <mesh geometry={nodes.Mesh_slice.geometry} material={materials.brownDarkest} />
        <mesh geometry={nodes.Mesh_slice_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_slice_2.geometry} material={materials.red} />
        <mesh geometry={nodes.Mesh_slice_3.geometry} material={materials.brownLight} />
        <mesh geometry={nodes.Mesh_slice_4.geometry} material={materials.purpleLight} />
        <mesh geometry={nodes.Mesh_slice_5.geometry} material={materials.brownDark} />
      </group>
      <group position={[-0.138, 0, -0.24]} rotation={[0, -Math.PI / 3, 0]}>
        <mesh geometry={nodes.Mesh_slice.geometry} material={materials.brownDarkest} />
        <mesh geometry={nodes.Mesh_slice_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_slice_2.geometry} material={materials.red} />
        <mesh geometry={nodes.Mesh_slice_3.geometry} material={materials.brownLight} />
        <mesh geometry={nodes.Mesh_slice_4.geometry} material={materials.purpleLight} />
        <mesh geometry={nodes.Mesh_slice_5.geometry} material={materials.brownDark} />
      </group>
      <group position={[-0.277, 0, 0]}>
        <mesh geometry={nodes.Mesh_slice.geometry} material={materials.brownDarkest} />
        <mesh geometry={nodes.Mesh_slice_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_slice_2.geometry} material={materials.red} />
        <mesh geometry={nodes.Mesh_slice_3.geometry} material={materials.brownLight} />
        <mesh geometry={nodes.Mesh_slice_4.geometry} material={materials.purpleLight} />
        <mesh geometry={nodes.Mesh_slice_5.geometry} material={materials.brownDark} />
      </group>
      <group position={[0.138, 0, -0.24]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
        <mesh geometry={nodes.Mesh_slice.geometry} material={materials.brownDarkest} />
        <mesh geometry={nodes.Mesh_slice_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_slice_2.geometry} material={materials.red} />
        <mesh geometry={nodes.Mesh_slice_3.geometry} material={materials.brownLight} />
        <mesh geometry={nodes.Mesh_slice_4.geometry} material={materials.purpleLight} />
        <mesh geometry={nodes.Mesh_slice_5.geometry} material={materials.brownDark} />
      </group>
      <group position={[0.277, 0, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Mesh_slice.geometry} material={materials.brownDarkest} />
        <mesh geometry={nodes.Mesh_slice_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_slice_2.geometry} material={materials.red} />
        <mesh geometry={nodes.Mesh_slice_3.geometry} material={materials.brownLight} />
        <mesh geometry={nodes.Mesh_slice_4.geometry} material={materials.purpleLight} />
        <mesh geometry={nodes.Mesh_slice_5.geometry} material={materials.brownDark} />
      </group>
      <group position={[-0.138, 0, 0.24]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Mesh_slice.geometry} material={materials.brownDarkest} />
        <mesh geometry={nodes.Mesh_slice_1.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_slice_2.geometry} material={materials.red} />
        <mesh geometry={nodes.Mesh_slice_3.geometry} material={materials.brownLight} />
        <mesh geometry={nodes.Mesh_slice_4.geometry} material={materials.purpleLight} />
        <mesh geometry={nodes.Mesh_slice_5.geometry} material={materials.brownDark} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cake.gltf')
